//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otomasyon {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resource1() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("otomasyon.resource1", typeof(resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Giriş Ekranı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s1 {
            get {
                return ResourceManager.GetString("s1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stok Durumu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s10 {
            get {
                return ResourceManager.GetString("s10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çalışan Bilgileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s11 {
            get {
                return ResourceManager.GetString("s11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Değiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s12 {
            get {
                return ResourceManager.GetString("s12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ekleme Sayfası benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s13 {
            get {
                return ResourceManager.GetString("s13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Listeleme Sayfası benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s14 {
            get {
                return ResourceManager.GetString("s14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s15 {
            get {
                return ResourceManager.GetString("s15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün Bilgileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s16 {
            get {
                return ResourceManager.GetString("s16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün Adı : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s17 {
            get {
                return ResourceManager.GetString("s17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün Adeti : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s18 {
            get {
                return ResourceManager.GetString("s18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ekle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s19 {
            get {
                return ResourceManager.GetString("s19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Adı : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s2 {
            get {
                return ResourceManager.GetString("s2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müşteri İşlemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s20 {
            get {
                return ResourceManager.GetString("s20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ad-Soyad : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s21 {
            get {
                return ResourceManager.GetString("s21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telefon No : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s22 {
            get {
                return ResourceManager.GetString("s22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İş Bilgileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s23 {
            get {
                return ResourceManager.GetString("s23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ev m2&apos;si : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s24 {
            get {
                return ResourceManager.GetString("s24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temizlik Türü : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s25 {
            get {
                return ResourceManager.GetString("s25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başlangıç Fiyatı : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s26 {
            get {
                return ResourceManager.GetString("s26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   m2 Fiyatı : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s27 {
            get {
                return ResourceManager.GetString("s27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toplam Fiyat : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s28 {
            get {
                return ResourceManager.GetString("s28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adres : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s29 {
            get {
                return ResourceManager.GetString("s29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifre : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s3 {
            get {
                return ResourceManager.GetString("s3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s30 {
            get {
                return ResourceManager.GetString("s30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güncelle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s31 {
            get {
                return ResourceManager.GetString("s31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Çalışana Aktar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s32 {
            get {
                return ResourceManager.GetString("s32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı Tipi : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s33 {
            get {
                return ResourceManager.GetString("s33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maaş : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s34 {
            get {
                return ResourceManager.GetString("s34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Meslek : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s35 {
            get {
                return ResourceManager.GetString("s35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alınan İş : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s36 {
            get {
                return ResourceManager.GetString("s36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Temizlikçi : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s37 {
            get {
                return ResourceManager.GetString("s37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Malzemeler : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s38 {
            get {
                return ResourceManager.GetString("s38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arşiv benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s39 {
            get {
                return ResourceManager.GetString("s39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s4 {
            get {
                return ResourceManager.GetString("s4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Demirbaş Bilgileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s40 {
            get {
                return ResourceManager.GetString("s40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Demirbaş Adı : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s41 {
            get {
                return ResourceManager.GetString("s41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Demirbaş Adeti : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s42 {
            get {
                return ResourceManager.GetString("s42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İş Tamamlandı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s43 {
            get {
                return ResourceManager.GetString("s43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel İş Bilgileri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s44 {
            get {
                return ResourceManager.GetString("s44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gelir : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s45 {
            get {
                return ResourceManager.GetString("s45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gider : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s46 {
            get {
                return ResourceManager.GetString("s46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kâr : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s47 {
            get {
                return ResourceManager.GetString("s47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personel İşlemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s48 {
            get {
                return ResourceManager.GetString("s48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alınan İşler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s49 {
            get {
                return ResourceManager.GetString("s49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yönetici İşlemleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s5 {
            get {
                return ResourceManager.GetString("s5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kim İçin? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s50 {
            get {
                return ResourceManager.GetString("s50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geri Bildirim : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s51 {
            get {
                return ResourceManager.GetString("s51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Malzemeler : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s52 {
            get {
                return ResourceManager.GetString("s52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Servis : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s53 {
            get {
                return ResourceManager.GetString("s53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ürün Türü : benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s54 {
            get {
                return ResourceManager.GetString("s54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Talep Edilen İşler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s6 {
            get {
                return ResourceManager.GetString("s6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Demirbaş Ürünler benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s7 {
            get {
                return ResourceManager.GetString("s7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gelir - Gider benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s8 {
            get {
                return ResourceManager.GetString("s8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Müşteri Geri Bildirimleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string s9 {
            get {
                return ResourceManager.GetString("s9", resourceCulture);
            }
        }
    }
}
